import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import RootProvider from '@app/_providers/root.provider'

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Auth.js Playwright Test',
  description: 'Generated by create next app  ',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${dmSans.variable} antialiased`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  )
}
